export const API_CONSTANTS = {
  USER: {
    REGISTER: "/register",
    VERIFY: "/verify?emailAddress={emailAddress}&deviceType={deviceType}",
    LOGIN: "/login",
    UPDATE_USER: "/tenant/users/:userId",
  },
  DEPARTMENT: {
    CREATE_DEPARTMENT: "/tenant/departments/",
    GET_DEPARTMENTS: "/tenant/departments/",
    GET_DEPARTMENT: (id: number) => `/tenant/departments/${id}`,
    UPDATE_DEPARTMENT: (id: number) => `/tenant/departments/${id}`,
    DELETE_DEPARTMENT: (id: number) => `/tenant/departments/${id}`,
  },
  STAFF: {
    CREATE_USER: "/tenant/users/",
    GET_USERS: "/tenant/users/",
    UPDATE_USER: (userId: string) => `/tenant/users/${userId}`,
    TOGGLE_USER_STATUS: (userId: string) => `/tenant/users/${userId}/status`,
    GRANT_MODULE_ACCESS: (userId: string) => `/tenant/users/${userId}/module`,
    UPDATE_MODULES_ACCESS: (moduleAccessId: string) =>
      `/tenant/users/module/${moduleAccessId}`,
    REMOVE_MODULE_ACCESS: (moduleAccessId: string) =>
      `/tenant/users/module/${moduleAccessId}`,
    ROLE_SCOPE_DROPDOWN: "/tenant/users/scopes",
  },
  MODULE: {
    MODULE_DROPDOWN: "/tenant/modules/dropdown",
  },
  TASK: {
    CREATE: "/tasks/",
    UPDATE: "/tasks/{taskId}",
    DELETE: "/tasks/{taskId}",
    GET_BY_ID: "/tasks/{taskId}",
    FILTER: "/tasks/filter",
    DROPDOWN: "/task/stages/dropdown",
    ADD_STAGE: "/task/stages/",
    DOCUMENT: {
      UPLOAD_URL: (taskId: string) => `/tasks/${taskId}/documents/upload-url`,
      VERIFY_UPLOAD: (docId: string) => `/tasks/documents/${docId}/verify`,
      DOWNLOAD_URL: (docId: string) => `/tasks/documents/${docId}/download-url`,
      DELETE: (docId: string) => `/tasks/documents/${docId}`,
    },
  },
  LEAD: {
    CREATE: "/lead/create",
    GET_ALL: "/lead/leads",
    UPDATE: "/lead/update",
    DELETE_BY_ID: "/lead/deleteLeadById",
    GET_BY_ID: "/lead/fetchLeadById",
    FILTER: "/lead/filter",
    IMPORT_LEAD: "/lead/upload",
    DROPDOWN: "/lead/dropdown",
    ADD_FOLLOWUP: "/lead/follow-up",
    LEAD_TRANSFER: "/lead/transfer",
    GET_ALL_WITH_FILTERS: "/lead/leads",
    ASSIGN_DROPDOWN: "/tenant/users/dropdown",
    CHANGE_PASSWORD: "/tenant/users/:userId/change-password",
    CHANGE_STATUS: "/lead/change-status",
  },
};
