import { ToastProvider } from '@/components/ui/toast';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { DashboardLayout } from '@/components/layout/dashboard-layout';

import { Providers } from '@/hooks/Providers';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
                <Providers>

        <DashboardLayout>
          {children}
          <Toaster />
        </DashboardLayout>
      </Providers>
      </body>
    </html>
  );
}
